export default {
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  UPDATE_KD_TOKEN: 'UPDATE_KD_TOKEN',
  REQUEST_KD_TOKEN_IN_PROGRESS: 'REQUEST_KD_TOKEN_IN_PROGRESS',
  REQUEST_KD_TOKEN_ERROR: 'REQUEST_KD_TOKEN_ERROR',
};
